version: "3.3"
services: 
    sql-server-db:
        container_name: sql-server-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        build:
          context: .
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "qwerty?123"
            ACCEPT_EULA: "Y"
        volumes:
            - ./db-data:/var/opt/mssql



